"""4

Revision ID: 46b82028bf6e
Revises: 99f311efbe57
Create Date: 2023-01-29 22:11:41.365652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b82028bf6e'
down_revision = '99f311efbe57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
