"""second

Revision ID: 99f311efbe57
Revises: fdd938b8c677
Create Date: 2023-01-27 16:46:18.485597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f311efbe57'
down_revision = 'fdd938b8c677'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'currency', ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'currency', type_='unique')
    # ### end Alembic commands ###
